//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JogoDaVelhaEntities : DbContext
    {
        public JogoDaVelhaEntities()
            : base("name=JogoDaVelhaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FilaEspera> FilaEspera { get; set; }
        public virtual DbSet<Jogo> Jogo { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Tabuleiro> Tabuleiro { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
